// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7gPfLPdFFs40CAKcbrnROBi2ACwEl5js',
    appId: '1:901782117520:web:9333857f1b22df82e54c15',
    messagingSenderId: '901782117520',
    projectId: 'mental-zen-71351',
    authDomain: 'mental-zen-71351.firebaseapp.com',
    storageBucket: 'mental-zen-71351.firebasestorage.app',
    measurementId: 'G-PRP1GXEKJ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt7YDXbEUSeKrs8iKOIatmgeC6BF0pPP8',
    appId: '1:901782117520:android:135e35aa8b6d5d09e54c15',
    messagingSenderId: '901782117520',
    projectId: 'mental-zen-71351',
    storageBucket: 'mental-zen-71351.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA678FzrU977mbVIfO0fStgQm_7WKjpkA0',
    appId: '1:901782117520:ios:49fa30a3e1228d04e54c15',
    messagingSenderId: '901782117520',
    projectId: 'mental-zen-71351',
    storageBucket: 'mental-zen-71351.firebasestorage.app',
    iosBundleId: 'com.example.mentaZen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA678FzrU977mbVIfO0fStgQm_7WKjpkA0',
    appId: '1:901782117520:ios:49fa30a3e1228d04e54c15',
    messagingSenderId: '901782117520',
    projectId: 'mental-zen-71351',
    storageBucket: 'mental-zen-71351.firebasestorage.app',
    iosBundleId: 'com.example.mentaZen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7gPfLPdFFs40CAKcbrnROBi2ACwEl5js',
    appId: '1:901782117520:web:81dc176e30ace5f3e54c15',
    messagingSenderId: '901782117520',
    projectId: 'mental-zen-71351',
    authDomain: 'mental-zen-71351.firebaseapp.com',
    storageBucket: 'mental-zen-71351.firebasestorage.app',
    measurementId: 'G-N29EQJEQYD',
  );

}